name: projeto2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.5
  - numpy=1.24.3
  - datasets=2.16.1
  - pillow=10.0.1
  - snappy
  - notebook
  - pip
  - pip:
      - torch==2.1.2
      - torchvision==0.16.2
      - tensorflow==2.15.0
      - transformers==4.37.1
      - watermark
      - scikit-learn
      - urllib3==1.26.16
      - accelerate==0.24.1
